version: '3'
services:
  php:
    build: ./src
    ports:
      - '8081:80'
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: note_taking
      MYSQL_USER: tutorials_user
      MYSQL_PASSWORD: changeme
    volumes:
      - database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - database

volumes:
  database:
